---
# Source: serverscom-rbs-csi/templates/controller.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbs-csi-controller
  namespace: kube-system
  labels:
    app: rbs-csi-controller
    app.kubernetes.io/name: serverscom-rbs-csi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbs-csi-controller
  template:
    metadata:
      labels:
        app: rbs-csi-controller
        app.kubernetes.io/name: serverscom-rbs-csi
    spec:
      serviceAccountName: rbs-csi-controller-sa
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.3.0
          args:
            - --csi-address=$(ADDRESS)
            - --v=2
            - --leader-election
            - --timeout=10m
            - --extra-create-metadata
            - --feature-gates=Topology=false
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.10.0
          args:
            - --v=2
            - --csi-address=$(ADDRESS)
            - --leader-election
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v2.0.0
          args:
            - --csi-address=$(ADDRESS)
            - --v=2
            - --leader-election
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: rbs-csi-driver
          image: ghcr.io/serverscom/rbs-csi-driver:v0.1.4
          imagePullPolicy: Always
          command:
            - /bin/rbs-csi-controller
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --v=2
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: SERVERSCOM_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: rbs-csi-secret
                  key: api-url
            - name: SERVERSCOM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rbs-csi-secret
                  key: api-token
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 100Mi
      volumes:
        - name: socket-dir
          emptyDir: {}
