---
# Source: serverscom-rbs-csi/templates/csi-driver.yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: rbs.csi.servers.com
  labels:
    app.kubernetes.io/name: serverscom-rbs-csi
spec:
  attachRequired: true
  podInfoOnMount: false
  volumeLifecycleModes:
    - Persistent
  fsGroupPolicy: File
  requiresRepublish: false
