apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: rbs.csi.servers.com
spec:
  attachRequired: true
  podInfoOnMount: false
  volumeLifecycleModes:
    - Persistent
  fsGroupPolicy: File
  requiresRepublish: false
