---
# Source: serverscom-rbs-csi/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbs-csi-controller-sa
  namespace: kube-system
  labels:
    app.kubernetes.io/name: serverscom-rbs-csi
---
# Source: serverscom-rbs-csi/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbs-csi-node-sa
  namespace: kube-system
  labels:
    app.kubernetes.io/name: serverscom-rbs-csi
---
# Source: serverscom-rbs-csi/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbs-csi-provisioner-role
  labels:
    app.kubernetes.io/name: serverscom-rbs-csi
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
    verbs:
      - get
      - list
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotcontents
    verbs:
      - get
      - list
  - apiGroups:
      - storage.k8s.io
    resources:
      - csinodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
# Source: serverscom-rbs-csi/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbs-csi-attacher-role
  labels:
    app.kubernetes.io/name: serverscom-rbs-csi
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - csinodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments/status
    verbs:
      - patch
---
# Source: serverscom-rbs-csi/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbs-csi-resizer-role
  labels:
    app.kubernetes.io/name: serverscom-rbs-csi
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims/status
    verbs:
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattributesclasses
    verbs:
      - get
      - list
      - watch
---
# Source: serverscom-rbs-csi/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbs-csi-node-driver-registrar-role
  labels:
    app.kubernetes.io/name: serverscom-rbs-csi
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
---
# Source: serverscom-rbs-csi/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbs-csi-provisioner-binding
  labels:
    app.kubernetes.io/name: serverscom-rbs-csi
subjects:
  - kind: ServiceAccount
    name: rbs-csi-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: rbs-csi-provisioner-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: serverscom-rbs-csi/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbs-csi-attacher-binding
  labels:
    app.kubernetes.io/name: serverscom-rbs-csi
subjects:
  - kind: ServiceAccount
    name: rbs-csi-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: rbs-csi-attacher-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: serverscom-rbs-csi/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbs-csi-resizer-binding
  labels:
    app.kubernetes.io/name: serverscom-rbs-csi
subjects:
  - kind: ServiceAccount
    name: rbs-csi-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: rbs-csi-resizer-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: serverscom-rbs-csi/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbs-csi-node-driver-registrar-binding
  labels:
    app.kubernetes.io/name: serverscom-rbs-csi
subjects:
  - kind: ServiceAccount
    name: rbs-csi-node-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: rbs-csi-node-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io
