{{- if not .Values.api.token -}}
{{- fail "api.token must be set to install rbs-csi" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: rbs-csi-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rbs-csi.labels" . | nindent 4 }}
stringData:
  api-url: {{ .Values.api.url | quote }}
  api-token: {{ .Values.api.token | quote }}
