// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen --destination ../mocks/iscsi_manager.go --package=mocks --source manager.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	iscsi "github.com/serverscom/rbs-csi-driver/pkg/iscsi"
	gomock "go.uber.org/mock/gomock"
)

// MockISCSIManager is a mock of ISCSIManager interface.
type MockISCSIManager struct {
	ctrl     *gomock.Controller
	recorder *MockISCSIManagerMockRecorder
	isgomock struct{}
}

// MockISCSIManagerMockRecorder is the mock recorder for MockISCSIManager.
type MockISCSIManagerMockRecorder struct {
	mock *MockISCSIManager
}

// NewMockISCSIManager creates a new mock instance.
func NewMockISCSIManager(ctrl *gomock.Controller) *MockISCSIManager {
	mock := &MockISCSIManager{ctrl: ctrl}
	mock.recorder = &MockISCSIManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISCSIManager) EXPECT() *MockISCSIManagerMockRecorder {
	return m.recorder
}

// CleanupTarget mocks base method.
func (m *MockISCSIManager) CleanupTarget(ctx context.Context, target *iscsi.TargetInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupTarget", ctx, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupTarget indicates an expected call of CleanupTarget.
func (mr *MockISCSIManagerMockRecorder) CleanupTarget(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupTarget", reflect.TypeOf((*MockISCSIManager)(nil).CleanupTarget), ctx, target)
}

// DiscoverTargets mocks base method.
func (m *MockISCSIManager) DiscoverTargets(ctx context.Context, portal string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscoverTargets", ctx, portal)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiscoverTargets indicates an expected call of DiscoverTargets.
func (mr *MockISCSIManagerMockRecorder) DiscoverTargets(ctx, portal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscoverTargets", reflect.TypeOf((*MockISCSIManager)(nil).DiscoverTargets), ctx, portal)
}

// GetDevice mocks base method.
func (m *MockISCSIManager) GetDevice(ctx context.Context, target *iscsi.TargetInfo) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevice", ctx, target)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevice indicates an expected call of GetDevice.
func (mr *MockISCSIManagerMockRecorder) GetDevice(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevice", reflect.TypeOf((*MockISCSIManager)(nil).GetDevice), ctx, target)
}

// IsLoggedIn mocks base method.
func (m *MockISCSIManager) IsLoggedIn(ctx context.Context, target *iscsi.TargetInfo) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLoggedIn", ctx, target)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLoggedIn indicates an expected call of IsLoggedIn.
func (mr *MockISCSIManagerMockRecorder) IsLoggedIn(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLoggedIn", reflect.TypeOf((*MockISCSIManager)(nil).IsLoggedIn), ctx, target)
}

// Login mocks base method.
func (m *MockISCSIManager) Login(ctx context.Context, target *iscsi.TargetInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockISCSIManagerMockRecorder) Login(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockISCSIManager)(nil).Login), ctx, target)
}

// Logout mocks base method.
func (m *MockISCSIManager) Logout(ctx context.Context, target *iscsi.TargetInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockISCSIManagerMockRecorder) Logout(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockISCSIManager)(nil).Logout), ctx, target)
}

// RescanDevice mocks base method.
func (m *MockISCSIManager) RescanDevice(ctx context.Context, devicePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RescanDevice", ctx, devicePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RescanDevice indicates an expected call of RescanDevice.
func (mr *MockISCSIManagerMockRecorder) RescanDevice(ctx, devicePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RescanDevice", reflect.TypeOf((*MockISCSIManager)(nil).RescanDevice), ctx, devicePath)
}

// WaitForDevice mocks base method.
func (m *MockISCSIManager) WaitForDevice(ctx context.Context, devicePath string, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForDevice", ctx, devicePath, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForDevice indicates an expected call of WaitForDevice.
func (mr *MockISCSIManagerMockRecorder) WaitForDevice(ctx, devicePath, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForDevice", reflect.TypeOf((*MockISCSIManager)(nil).WaitForDevice), ctx, devicePath, timeout)
}
