// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen --destination ../mocks/mount_manager.go --package=mocks --source manager.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	mount "github.com/serverscom/rbs-csi-driver/pkg/mount"
	gomock "go.uber.org/mock/gomock"
)

// MockMountManager is a mock of MountManager interface.
type MockMountManager struct {
	ctrl     *gomock.Controller
	recorder *MockMountManagerMockRecorder
	isgomock struct{}
}

// MockMountManagerMockRecorder is the mock recorder for MockMountManager.
type MockMountManagerMockRecorder struct {
	mock *MockMountManager
}

// NewMockMountManager creates a new mock instance.
func NewMockMountManager(ctrl *gomock.Controller) *MockMountManager {
	mock := &MockMountManager{ctrl: ctrl}
	mock.recorder = &MockMountManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMountManager) EXPECT() *MockMountManagerMockRecorder {
	return m.recorder
}

// BindMount mocks base method.
func (m *MockMountManager) BindMount(ctx context.Context, sourcePath, targetPath string, options []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindMount", ctx, sourcePath, targetPath, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindMount indicates an expected call of BindMount.
func (mr *MockMountManagerMockRecorder) BindMount(ctx, sourcePath, targetPath, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindMount", reflect.TypeOf((*MockMountManager)(nil).BindMount), ctx, sourcePath, targetPath, options)
}

// FormatAndMountDevice mocks base method.
func (m *MockMountManager) FormatAndMountDevice(ctx context.Context, devicePath, targetPath, fsType string, mountOptions []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatAndMountDevice", ctx, devicePath, targetPath, fsType, mountOptions)
	ret0, _ := ret[0].(error)
	return ret0
}

// FormatAndMountDevice indicates an expected call of FormatAndMountDevice.
func (mr *MockMountManagerMockRecorder) FormatAndMountDevice(ctx, devicePath, targetPath, fsType, mountOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatAndMountDevice", reflect.TypeOf((*MockMountManager)(nil).FormatAndMountDevice), ctx, devicePath, targetPath, fsType, mountOptions)
}

// GetMountInfo mocks base method.
func (m *MockMountManager) GetMountInfo(targetPath string) (*mount.MountInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMountInfo", targetPath)
	ret0, _ := ret[0].(*mount.MountInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMountInfo indicates an expected call of GetMountInfo.
func (mr *MockMountManagerMockRecorder) GetMountInfo(targetPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMountInfo", reflect.TypeOf((*MockMountManager)(nil).GetMountInfo), targetPath)
}

// IsMounted mocks base method.
func (m *MockMountManager) IsMounted(targetPath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMounted", targetPath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMounted indicates an expected call of IsMounted.
func (mr *MockMountManagerMockRecorder) IsMounted(targetPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMounted", reflect.TypeOf((*MockMountManager)(nil).IsMounted), targetPath)
}

// Mount mocks base method.
func (m *MockMountManager) Mount(ctx context.Context, devicePath, targetPath, fsType string, options []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mount", ctx, devicePath, targetPath, fsType, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mount indicates an expected call of Mount.
func (mr *MockMountManagerMockRecorder) Mount(ctx, devicePath, targetPath, fsType, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mount", reflect.TypeOf((*MockMountManager)(nil).Mount), ctx, devicePath, targetPath, fsType, options)
}

// ResizeFilesystem mocks base method.
func (m *MockMountManager) ResizeFilesystem(ctx context.Context, devicePath, fsType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResizeFilesystem", ctx, devicePath, fsType)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResizeFilesystem indicates an expected call of ResizeFilesystem.
func (mr *MockMountManagerMockRecorder) ResizeFilesystem(ctx, devicePath, fsType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResizeFilesystem", reflect.TypeOf((*MockMountManager)(nil).ResizeFilesystem), ctx, devicePath, fsType)
}

// ResizeFilesystemAtPath mocks base method.
func (m *MockMountManager) ResizeFilesystemAtPath(ctx context.Context, mountPath, fsType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResizeFilesystemAtPath", ctx, mountPath, fsType)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResizeFilesystemAtPath indicates an expected call of ResizeFilesystemAtPath.
func (mr *MockMountManagerMockRecorder) ResizeFilesystemAtPath(ctx, mountPath, fsType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResizeFilesystemAtPath", reflect.TypeOf((*MockMountManager)(nil).ResizeFilesystemAtPath), ctx, mountPath, fsType)
}

// Unmount mocks base method.
func (m *MockMountManager) Unmount(ctx context.Context, targetPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmount", ctx, targetPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmount indicates an expected call of Unmount.
func (mr *MockMountManagerMockRecorder) Unmount(ctx, targetPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmount", reflect.TypeOf((*MockMountManager)(nil).Unmount), ctx, targetPath)
}
