// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen --destination ../mocks/rbs_service.go --package=mocks --source service.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	serverscom "github.com/serverscom/serverscom-go-client/pkg"
	gomock "go.uber.org/mock/gomock"
)

// MockRBSService is a mock of RBSService interface.
type MockRBSService struct {
	ctrl     *gomock.Controller
	recorder *MockRBSServiceMockRecorder
	isgomock struct{}
}

// MockRBSServiceMockRecorder is the mock recorder for MockRBSService.
type MockRBSServiceMockRecorder struct {
	mock *MockRBSService
}

// NewMockRBSService creates a new mock instance.
func NewMockRBSService(ctrl *gomock.Controller) *MockRBSService {
	mock := &MockRBSService{ctrl: ctrl}
	mock.recorder = &MockRBSServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRBSService) EXPECT() *MockRBSServiceMockRecorder {
	return m.recorder
}

// CreateVolume mocks base method.
func (m *MockRBSService) CreateVolume(ctx context.Context, req serverscom.RemoteBlockStorageVolumeCreateInput) (*serverscom.RemoteBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVolume", ctx, req)
	ret0, _ := ret[0].(*serverscom.RemoteBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVolume indicates an expected call of CreateVolume.
func (mr *MockRBSServiceMockRecorder) CreateVolume(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVolume", reflect.TypeOf((*MockRBSService)(nil).CreateVolume), ctx, req)
}

// DeleteVolume mocks base method.
func (m *MockRBSService) DeleteVolume(ctx context.Context, volumeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVolume", ctx, volumeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVolume indicates an expected call of DeleteVolume.
func (mr *MockRBSServiceMockRecorder) DeleteVolume(ctx, volumeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVolume", reflect.TypeOf((*MockRBSService)(nil).DeleteVolume), ctx, volumeID)
}

// FindFlavorByName mocks base method.
func (m *MockRBSService) FindFlavorByName(ctx context.Context, locationID int, name string) (*serverscom.RemoteBlockStorageFlavor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFlavorByName", ctx, locationID, name)
	ret0, _ := ret[0].(*serverscom.RemoteBlockStorageFlavor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFlavorByName indicates an expected call of FindFlavorByName.
func (mr *MockRBSServiceMockRecorder) FindFlavorByName(ctx, locationID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFlavorByName", reflect.TypeOf((*MockRBSService)(nil).FindFlavorByName), ctx, locationID, name)
}

// FindLocationByName mocks base method.
func (m *MockRBSService) FindLocationByName(ctx context.Context, name string) (*serverscom.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLocationByName", ctx, name)
	ret0, _ := ret[0].(*serverscom.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLocationByName indicates an expected call of FindLocationByName.
func (mr *MockRBSServiceMockRecorder) FindLocationByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLocationByName", reflect.TypeOf((*MockRBSService)(nil).FindLocationByName), ctx, name)
}

// FindVolumeByLabel mocks base method.
func (m *MockRBSService) FindVolumeByLabel(ctx context.Context, labelKey, labelValue string) (*serverscom.RemoteBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVolumeByLabel", ctx, labelKey, labelValue)
	ret0, _ := ret[0].(*serverscom.RemoteBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindVolumeByLabel indicates an expected call of FindVolumeByLabel.
func (mr *MockRBSServiceMockRecorder) FindVolumeByLabel(ctx, labelKey, labelValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVolumeByLabel", reflect.TypeOf((*MockRBSService)(nil).FindVolumeByLabel), ctx, labelKey, labelValue)
}

// GetVolume mocks base method.
func (m *MockRBSService) GetVolume(ctx context.Context, volumeID string) (*serverscom.RemoteBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolume", ctx, volumeID)
	ret0, _ := ret[0].(*serverscom.RemoteBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolume indicates an expected call of GetVolume.
func (mr *MockRBSServiceMockRecorder) GetVolume(ctx, volumeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolume", reflect.TypeOf((*MockRBSService)(nil).GetVolume), ctx, volumeID)
}

// GetVolumeCredentials mocks base method.
func (m *MockRBSService) GetVolumeCredentials(ctx context.Context, volumeID string) (*serverscom.RemoteBlockStorageVolumeCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolumeCredentials", ctx, volumeID)
	ret0, _ := ret[0].(*serverscom.RemoteBlockStorageVolumeCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolumeCredentials indicates an expected call of GetVolumeCredentials.
func (mr *MockRBSServiceMockRecorder) GetVolumeCredentials(ctx, volumeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolumeCredentials", reflect.TypeOf((*MockRBSService)(nil).GetVolumeCredentials), ctx, volumeID)
}

// ResetVolumeCredentials mocks base method.
func (m *MockRBSService) ResetVolumeCredentials(ctx context.Context, volumeID string) (*serverscom.RemoteBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetVolumeCredentials", ctx, volumeID)
	ret0, _ := ret[0].(*serverscom.RemoteBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetVolumeCredentials indicates an expected call of ResetVolumeCredentials.
func (mr *MockRBSServiceMockRecorder) ResetVolumeCredentials(ctx, volumeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetVolumeCredentials", reflect.TypeOf((*MockRBSService)(nil).ResetVolumeCredentials), ctx, volumeID)
}

// UpdateVolume mocks base method.
func (m *MockRBSService) UpdateVolume(ctx context.Context, volumeID string, req serverscom.RemoteBlockStorageVolumeUpdateInput) (*serverscom.RemoteBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVolume", ctx, volumeID, req)
	ret0, _ := ret[0].(*serverscom.RemoteBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVolume indicates an expected call of UpdateVolume.
func (mr *MockRBSServiceMockRecorder) UpdateVolume(ctx, volumeID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVolume", reflect.TypeOf((*MockRBSService)(nil).UpdateVolume), ctx, volumeID, req)
}
